service: my-mongodb-service

provider:
  name: mongodb
  runtime: nodejs14.x

resources:
  east-cluster:
    type: AtlasCluster
    name: east-cluster
    region: US_EAST_1
    tier: M10
    provider: AWS
    version: "7.0"
  west-cluster:
    type: AtlasCluster
    name: west-cluster
    region: US_WEST
    tier: M20
    provider: AZURE
    version: "7.0"

plugins:
- serverless-dotenv-plugin
- ./sls-mongodb-provider


